# The app's name, which must be unique within the project.
name: "landing-connect"

# The language and version for your app.
type: "nodejs:18"
web:
  commands:
    start: sleep infinity
  locations:
    "/":
      root: "public"
      index: ["index.html"]
      scripts: false
      allow: true
