import { danger, message, warn, fail } from 'danger'

// Titles should include the correct prefix tag
if (
  !danger.github.pr.title.match(/^\[(?:Fixed|Added|Changed|Migrations|Security|Other|Removed)\]/)
) {
  fail(
    'Please provide a valid PR title label: [Added]/[Fixed]/[Changed]/[Security]/[Other]/[Removed]'
  )
}
const existingLabels = danger.github.pr.labels.map(({ name }) => name)

//  The title should include the JIRA ticket unless is a dependabot PR
if (existingLabels.includes('dependencies')) {
  message('PR autogenerated by dependabot')
} else if (!danger.github.pr.title.match(/^\[.*\]\s?\[BEL-\d+|PXP-\d+|PAY-\d+|INF-\d+\]/)) {
  fail(
    'Please provide a valid Jira ticket ID associated to this PR: [BEL-XXXX], [PAY-XXXX] or [INF-XXXX]'
  )
}

if (!danger.github.pr.body) {
  warn(':grey_question: This pull request needs a description.')
}


message('One approval required for merging :smiley:')
