import { danger, message, warn, fail } from 'danger'

// Titles should include the correct prefix tag
if (
  !danger.github.pr.title.match(/^\[(?:Fixed|Added|Changed|Migrations|Security|Other|Removed)\]/)
) {
  fail(
    'Please provide a valid PR title label: [Added]/[Fixed]/[Changed]/[Security]/[Other]/[Removed]'
  )
}
const existingLabels = danger.github.pr.labels.map(({ name }) => name)

//  The title should include the JIRA ticket unless is a dependabot PR
if (existingLabels.includes('dependencies')) {
  message('PR autogenerated by dependabot')
} else if (!danger.github.pr.title.match(/^\[.*\]\s?\[BEL-\d+|PXP-\d+|PAY-\d+|INF-\d+\]/)) {
  fail(
    'Please provide a valid Jira ticket ID associated to this PR: [BEL-XXXX], [PAY-XXXX] or [INF-XXXX]'
  )
}

if (!danger.github.pr.body) {
  warn(':grey_question: This pull request needs a description.')
}

// Warns if there are changes to package.json, and tags the team.
const packageChanged = danger.git.modified_files.indexOf('package.json') > -1
if (!packageChanged) {
  const title = ':lock: package.json'
  const idea =
    "Increasing the version it's not mandatory only if the one in master has not been released yet!"
  warn(`${title} - <i>${idea}</i>`)
}

message('One approval required for merging :smiley:')
