name: Danger PR
on:
  pull_request:
    types: [opened, reopened, edited, synchronize, labeled]
    branches: [master]
permissions:
  contents: read
  repository-projects: read
  packages: read
  pull-requests: write
  statuses: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Run Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
